FROM python:3.9

WORKDIR /app

RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx libglib2.0-0 ffmpeg

COPY backend/requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV PYTHONPATH=/app/backend

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]